spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}
server:
  port: 8080

zuul:
  prefix: /proxy
  retryable: true


hystrix:
  command:
    default:
      execution.isolation:
        semaphore:
          maxConcurrentRequests: 50
        thread:
          timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: info,health,hystrix.stream
