spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xa_ticket?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

server:
  port: 10003

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream

swagger.api:
  enabled: true
  title: "Ticket Service"
  description: "Sample Micro-service - order service for demonstration purpose"
  terms-of-service-url: "https://oauth.net/2"
  version: "v1.0.0"
  controller:
    base-package: "org.akj.springboot"
  contact:
    name: "Jamie Zhang"
    email: "akjamie.zhang@outlook.com"
